FROM python:3.9-slim  # Base image with Python 3.9

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt  # Install dependencies

COPY .  .
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]